name: Deploy to Staging

on:
  push:
    branches: [ stg-release ]
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-1
  TERRAFORM_VERSION: 1.5.0

jobs:
  terraform:
    name: Deploy to Staging Environment
    runs-on: ubuntu-latest
    environment: staging
    
    defaults:
      run:
        working-directory: terraform/stg

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="terraform.tfvars" -out=tfplan
        env:
          TF_VAR_db_password: ${{ secrets.STG_DB_PASSWORD }}

      - name: Wait for Manual Approval
        if: github.ref == 'refs/heads/stg-release'
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: ${{ vars.STAGING_APPROVERS }}
          minimum-approvals: 1
          issue-title: "Deploy to Staging Environment"
          issue-body: |
            Please review the Terraform plan and approve this deployment to the staging environment.
            
            **Environment:** Staging
            **Branch:** ${{ github.ref_name }}
            **Commit:** ${{ github.sha }}
            
            Review the workflow logs for the Terraform plan details.

      - name: Terraform Apply
        if: github.ref == 'refs/heads/stg-release'
        run: terraform apply -auto-approve tfplan

      - name: Output ALB DNS
        if: github.ref == 'refs/heads/stg-release'
        run: |
          echo "ALB DNS Name: $(terraform output -raw alb_dns_name)"
          echo "ALB_DNS_NAME=$(terraform output -raw alb_dns_name)" >> $GITHUB_ENV

      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Staging deployment ${{ job.status }}!
            ALB DNS: ${{ env.ALB_DNS_NAME }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}