name: Terraform Lint

on:
  pull_request:
    paths:
      - 'terraform/**'
      - 'modules/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Validate
        run: |
          set -e
          for dir in terraform/environments/*; do
            (cd "$dir" && terraform init -backend=false && terraform validate)
          done
